### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by Denys-Panchuck** [Denys-Panchuck/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by 85coba** [comment]
I am a web developer. I've got some experience in MySQL, PHP, HTML, JavaScript.
I've been working with frameworks such as Laravel, VueJs and little bit with Flutter for mobile developing.
I haven't got many years of experience in developing. But I'm a quick learner, responsible and have an ability and desire to work hard on big and intresting projects.

**Comment by Denys-Panchuck** [comment]
You are best, thx.
