### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by Denys-Panchuck** [Denys-Panchuck/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by 85coba** [comment]
Email: uapanchude@gmail.com
Linkedin:  https://www.linkedin.com/in/denys-panchuk/
