### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by Denys-Panchuck** [Denys-Panchuck/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by 85coba** [comment]
EXPERIENCE

2004
Began my career as a co-founder of a little computer game club.

2005
Worked in Nestle Ukraine as SAP WM Administrator. 
Responsibility:
 - Providing support SAP LE-WM on Distribution Center, 
 - Monitoring of SAP standard jobs, 
 - Execute system health check, 
 - Conducting regular WH inventories;

2012
Founded a company of selling car parts. It was a small business, just four employees.

2017
Worked in building company Shynaka Ukraine as the chief of a large department, this one include wood factory, warehouse, transport and logistic, sales department. Also was responsible for all IT issues in the company.

2019
Began working on freelance exchange Upwork.com as freelancer web-developer.

2020
Worked on firmply.com project as junior developer.

EDUCATION

2003 
Enrolled in the Lesya Ukrainka Eastern European National University on mathematics faculty.

**Comment by Denys-Panchuck** [comment]
Awesome!
