### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by Denys-Panchuck** [Denys-Panchuck/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by 85coba** [comment]
LANGUAGES
:ukraine:  УКРАЇНСЬКА :ru: РУССКИЙ :us:  ENGLISH (Pre-intermediate)

SKILLS

HTML, Object Oriented PHP, Laravel, JavaScript, Vue.js, Vuex, MySQL, Restful API.

PERSONAL QUALITIES

Responsibility, Learnability, Purposefulness, Stress resistance.

SPECIAL WISHES

Do not work at night on weekends)

**Comment by Denys-Panchuck** [comment]
Brilliant!!!
